### ISSUE TITLE
Simple script to run ACNe for image matching on a single image pairs request

### ISSUE THREAD

**Issue by fb82** [vcg-uvic/acne#2]
Hi,
could you please provide a simple script to run ACNe for image matching on a single image pairs (i.e. script input: 1st image keypoints & descriptors, 2nd image keypoints & descriptors, and what to compute among the homography/fundamental/essential matrices --> script output: keypoint correspondences)?

Thanks in advance,
Fabio

**Comment by wsunid** [comment]
Hi Fabio,

It sounds like a good idea to make such demo. Yes, I will make one and let you know here once it is finished.

Thanks,
Weiwei.

**Comment by wsunid** [comment]
Hi Fabio,

I have added a demo of matching two images with ACNe. Hope it can give you the idea of image matching on a single pair :))

Feel free to let me know if you need any further information.

Thanks,
Weiwei.

**Comment by fb82** [comment]
Thanks! I will be very useful for my experiments!
