### ISSUE TITLE
Code for the line fitting experiment

### ISSUE THREAD

**Issue by georg-bn** [vcg-uvic/acne#4]
Hi,

Thank you for your great work and making it available here.

I would like to compare a network design to the line fitting experiment in your paper. Would it be at all possible for you to share your code for that experiment?

Thanks.
/Georg

**Comment by wsunid** [comment]
Hi,

Thanks for your interest in our work!!

I am preparing the code and will release it as soon as I can -- kinda busy with my other project :)  I will appreciate your patience.

All the best,
Weiwei.

**Comment by georg-bn** [comment]
Thank you, that's amazing!

**Comment by wsunid** [comment]
Hello Georg,

Sorry for the late. And thanks a lot for your patience! 

The code for line fitting still looks messy. But I'm buried in my other ongoing projects for now. I might not be available until the NeurIPS deadline. But please feel free to let me know via Email if you need help. 

Thanks!
Weiwei.

**Comment by wsunid** [comment]
Hey, the line data is shared here: https://github.com/acne/line-fitting
Sorry for the late!

Best,
Weiwei.

**Comment by georg-bn** [comment]
Thank you for your help!

Best,
Georg
