### ISSUE TITLE
The lines fitting data.

### ISSUE THREAD

**Issue by DIVE128** [vcg-uvic/acne#5]
thank you for your work and sharing.
The lines fitting datas for training and testing does not include in the project , could you please provide a link to download it?

**Comment by wsunid** [comment]
Hi, thanks for your interest in our work. 

The line data is synthetic data -- we generate it on the fly.  I will release the line-fitting experiments as soon as I can. So that you can play with it. Stay tuned.

Thanks,
Weiwei.

**Comment by wsunid** [comment]
The data for line fitting is shared here:  https://github.com/acne/line-fitting
Sorry for the late!

Best,
Weiwei.
